### ISSUE TITLE
Battery life indication??

### ISSUE THREAD

**Issue by enoch-chang** [enoch-chang/Flashing-Lights-Project#1]
Hi Dr. Palmeri

Please refer to the circuit diagram found in the 'Electronics' folder.

Been reading many different articles about how to do this... seems like a voltage division at the source seemed like the most common implementation method. I have this going into an analog input pin of the Arduino and then after some processing, representing that information as a PWM and to a separate LED. Just wanted to make sure this implementation is valid... or if you have any suggestions, I'd really appreciate that.

On a side note, I have a bypass capacitor before the regulator to prevent it from blowing out. Is this placed correctly? I noticed that Jeff from Blur had capacitors before AND after his regulator. 

Thanks!

**Comment by mlp6** [comment]
Looks functional, though the voltage divider approach will come at the expense of a constant current draw from the battery, which will decrease its life.

The cap after the voltage regulator is actually more important than the one before since the regulator itself will do a lot of the heavy lifting in mapping the voltage to the desired output.  The second cap helps maintain that output voltage.

**Comment by mlp6** [comment]
Yep!
